### ISSUE TITLE
Remove assert checks 

### ISSUE THREAD

**Issue by ab93** [numaproj/numalogic#169]
**Describe the bug**
Some parts of the code has assertion checks. Need to replace them with normal exceptions.

The two places where this is currently seen is:
- [conv.py](https://github.com/numaproj/numalogic/blob/main/numalogic/models/autoencoder/variants/conv.py)
- [static.py](https://github.com/numaproj/numalogic/blob/main/numalogic/models/threshold/_static.py)

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by Subhashini014** [comment]
could you please assign me this issue.
