### ISSUE TITLE
Fix loss logging to return average of all batches in epoch

### ISSUE THREAD

**Issue by ab93** [numaproj/numalogic#53]
**Describe the bug**
The logged loss while training the autoencoder models, does not represent the average loss for the whole batch. Instead currently it just returns the last batch's loss.

**Expected behavior**
The loss returned should be an average of the loss of all the batches in the epoch.

**Comment by diego-ponce** [comment]
Can you assign this to me? I have created https://github.com/numaproj/numalogic/pull/55 to attempt to fix this issue.

**Comment by ab93** [comment]
Of course! :)
