### ISSUE TITLE
Improve SparseAEPipeline docs

### ISSUE THREAD

**Issue by ab93** [numaproj/numalogic#59]
Add docstrings to the SparseAEPipeline. It follows the paper: https://web.stanford.edu/class/cs294a/sparseAutoencoder.pdf

**Comment by REETI-SARUP** [comment]
Hi @ab93, 
Wanted to confirm if this issue refers to adding the docstrings for the `SparseAEPipeline` class & its methods in the `numalogic/models/autoencoder/pipeline.py` file

Could you please assign this issue to me, thanks.

**Comment by ab93** [comment]
Hey @REETI-SARUP welcome! Yes that is correct! Assigning this to you! :)

**Comment by REETI-SARUP** [comment]
Hi @ab93, 
I've raised the PR for adding docstrings for the SparseAEPipeline class & its methods, please review / merge:
https://github.com/numaproj/numalogic/pull/67
