### ISSUE TITLE
Boto3 dependency for mlflow

### ISSUE THREAD

**Issue by s0nicboOm** [numaproj/numalogic#66]
# Summary
Add boto3 dependency along with mlflow in extras. Mlflow depends upon boto3 and is not installed along with mlflow package

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by ab93** [comment]
Closing this since this is not really numalogic should handle. It should be installed separately by the consuming library, e.g. numaprom
