### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by ab93** [numaproj/numalogic#68]
- Add workflow to make sure 3.11 build succeeds
- Update pyproject.toml file to support python 3.11.x versions

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by tcchawla** [comment]
Can I work on this issue?

**Comment by ab93** [comment]
Of course @tcchawla . Let me know if you need any help or info on this. :)

**Comment by tcchawla** [comment]
Hello @ab93, I have created a PR solving this issue #72.

**Comment by ab93** [comment]
hi @tcchawla thank you so much for the PR. Unfortunately, torch does not support 3.11 yet. Can you pick another issue for the time being. Would love some help on some of the other issues. :)

**Comment by tcchawla** [comment]
Sure @ab93, I will take other issues.

**Comment by tcchawla** [comment]
Hey @ab93, PyTorch has rolled out `beta` for `Python 3.11` - here https://pytorch.org/blog/PyTorch-1.13-release/
Also, in their nightly builds they have built support for 3.11 version - https://github.com/pytorch/pytorch/issues/86566#issuecomment-1273440939

**Comment by ab93** [comment]
Correct. :) Good find. We avoid nightly versions to keep the library stable. Let's keep an eye out, and merge this when they push out a stable version.
